ALTER TABLE "chapters" ALTER COLUMN "part_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "summary" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "character_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "arc_position" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "contributes_to_macro_arc" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "focus_characters" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "adversity_type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "virtue_type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "seeds_planted" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "seeds_resolved" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "connects_to_previous_chapter" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "creates_next_adversity" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "published_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "chapters" ALTER COLUMN "scheduled_for" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "parts" ALTER COLUMN "summary" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "parts" ALTER COLUMN "character_arcs" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "parts" ALTER COLUMN "order_index" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "summary" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "cycle_phase" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "emotional_beat" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "character_focus" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "setting_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "sensory_anchors" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "dialogue_vs_description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "suggested_length" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "content" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "auto_publish" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "comic_panel_count" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ALTER COLUMN "comic_version" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "summary" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "adversity_elements" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "symbolic_meaning" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "cycle_amplification" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "mood" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "emotional_resonance" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "sensory" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "architectural_style" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "visual_references" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "settings" ALTER COLUMN "color_palette" SET NOT NULL;